# Site Settings
name: Kunj Sangani
title: Kunj Sangani | Blog on Microsoft 365
description: Blog on Microsoft 365 with focus on SharePoint and related topics.
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
email: sangani.kunj@gmail.com
disqus_username: https-kunj-sangani-github-io
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml


# Social Media Settings
# Remove the item if you don't need it
github_username: kunj-sangani
facebook_username: kunj.sangani
twitter_username: sanganikunj
instagram_username: kunj_sangani
linkedin_username: kunj-sangani
medium_username: sangani.kunj


# Posts Settings
show_time_bar: true
show_modal_on_exit: false
show_modal_on_finish_post: true
two_columns_layout: true


# Advanced Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"
language: "en"
categories_folder: category
sent_message_url: "/contact/message-sent/"


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
paginate_path: "/page/:num/"
show_get_theme_btn: false
use_logo: false

# Content paginator
paginate_content:
  enabled: true
  debug: false
  collections:
    - posts
  auto: false
  separator: "--page-break--"
  permalink: "/:num/"
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true

# SASS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content

# Exclude my node related stuff
exclude: [
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md'
]

# Theme
version: v3.1.0
